encoding: utf-8

# SEO相关信息
title: rainoffallingstar's Blog
description: rainoffallingstar的个人博客
keywords: Blog,Reading,Html,JavaScript
author: rainoffallingstar
footerText: 'Copyright © rainoffallingstar 版权所有  转载请注明出处'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://rainoffallingstar.gitee.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址：https://support.qq.com/product/366690
# tape质问箱地址，会在chat页面重定向到该地址：https://www.tapechat.net/uu/7TWZJS/GJ1110Q8
tucaoUrl: https://www.tapechat.net/uu/7TWZJS/GJ1110Q8

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true

# 友情链接
links:
  - title: 禾道亭
    url: https://hedaozi.com/
  
